application: http://github.com/nikcub
version: 1
runtime: python
api_version: 1

handlers:
# Most browsers request favicon
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon
  expiration: 10000d

# Most bots request robots
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  mime_type: text/plain
  expiration: 10000d

# Static file mappings
# Set an infinite expiration on static files for browser caching. When you update a static file
# you need to increment the version number in the request so that the browser requests the new
# version. For eg.
#
# <link id="css-core" rel="stylesheet" href="/css/style.css?2010100101" type="text/css">
#
# Edit the file, save and then incremement the counter so browsers re-request:
#
# <link id="css-core" rel="stylesheet" href="/css/style.css?2010100102" type="text/css">
#
# This will save you a lot of bandwidth quota
#
- url: /css
  mime_type: text/css
  expiration: 10000d
  static_dir: static/css
- url: /img
  expiration: 10000d
  static_dir: static/img
- url: /js
  static_dir: static/js
  expiration: 10000d

# Catch-all for static files
- url: /static
  static_dir: static

# Catch-all to the app for all other requests
# url is a regexp
- url: .*
  script: main.py

# These are custom error handlers
error_handlers:
- file: templates/server_error.html
- error_code: over_quota
  file: templates/server_error.html
- error_code: dos_api_denial
  file: templates/server_error.html
- error_code: timeout
  file: templates/server_error.html

# Builtins to allow you to admin your app at the url 
builtins:
- datastore_admin: on
- appstats: on
- admin_redirect: on

# Ignore the following files on deploy (edito files, git files, pyo files etc.)
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?index\.yaml
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/git/.*
- ^(.*/)?.*/svn/.*
- ^(.*/)?\..*
- ^(.*/)?README$
- ^(.*/)?.*\.bak$
